[package]
name = "llm-playground"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
macroquad = "0.4"
tiled = { version = "0.14", features = ["wasm"] }
