[package]
name = "llm-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
macroquad = "0.4"
rand = "0.8.5"
tiled = { version = "0.11.2", features = ["wasm"] }
